// This file is automatically generated. Do not modify it manually.
// Code generated .* DO NOT EDIT.

export const id = 'com.github.manland.mattermost-plugin-gitlab';
export const version = '1.4.0';
