// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.github.manland.mattermost-plugin-gitlab",
	Version: "1.1.0",
}
